import { CalendarDays, Plus, Save, Trash2, UserPlus } from 'lucide-react'
import { PageHeader, Panel } from '../components/AppChrome.jsx'

const tabs = ['League Settings', 'Scoring', 'Rosters', 'Schedule', 'Managers', 'Draft', 'Permissions']

export function CommissionerView({ data, setData, commissionerTab, setCommissionerTab, onSave }) {
  const updateLeague = (field, value) => setData((current) => ({ ...current, league: { ...current.league, [field]: value } }))
  const updateSetting = (field, value) => setData((current) => ({ ...current, settings: { ...current.settings, [field]: value } }))
  const updateScore = (id, field, value) => setData((current) => ({ ...current, scoringRules: current.scoringRules.map((rule) => rule.id === id ? { ...rule, [field]: field === 'points' ? Number(value) : value } : rule) }))
  const updateStarter = (slot, value) => setData((current) => ({ ...current, settings: { ...current.settings, starters: { ...current.settings.starters, [slot]: Number(value) } } }))
  const togglePermission = (key) => setData((current) => ({ ...current, settings: { ...current.settings, permissions: { ...current.settings.permissions, [key]: !current.settings.permissions[key] } } }))
  const addScore = () => setData((current) => ({ ...current, scoringRules: [...current.scoringRules, { id: Math.max(...current.scoringRules.map((rule) => rule.id), 0) + 1, category: 'Custom scoring', rule: 'Each', points: 1 }] }))
  const addManager = () => setData((current) => ({ ...current, teams: [...current.teams, { id: `invite-${Date.now()}`, name: 'New Team', manager: 'Invite pending', wins: 0, losses: 0, points: 0, waiver: current.teams.length + 1 }] }))

  return <>
    <PageHeader title="Commissioner" description="Configure Liquid Crew and control every part of the league." actions={<button className="button primary" type="button" onClick={onSave}><Save /> Save changes</button>} />
    <div className="commissioner-tabs" role="tablist">{tabs.map((tab) => <button key={tab} type="button" role="tab" aria-selected={commissionerTab === tab} onClick={() => setCommissionerTab(tab)}>{tab}</button>)}</div>

    {commissionerTab === 'League Settings' && <div className="settings-grid">
      <Panel title="League Identity"><div className="form-grid"><label className="wide">League name<input value={data.league.name} onChange={(e) => updateLeague('name', e.target.value)} /></label><label>Season<input type="number" value={data.league.season} onChange={(e) => updateLeague('season', Number(e.target.value))} /></label><label>Number of teams<input type="number" min="4" max="32" value={data.league.teamCount} onChange={(e) => updateLeague('teamCount', Number(e.target.value))} /></label><label className="wide">Scoring type<select value={data.league.format} onChange={(e) => updateLeague('format', e.target.value)}><option>Head-to-head points</option><option>Rotisserie</option><option>Best ball</option></select></label></div></Panel>
      <Panel title="Transaction Settings"><div className="form-grid"><label className="wide">Waiver type<select value={data.settings.waiverType} onChange={(e) => updateSetting('waiverType', e.target.value)}><option>Inverse standings</option><option>FAAB</option><option>Rolling list</option></select></label><label>Processing days<input type="number" min="0" value={data.settings.waiverDays} onChange={(e) => updateSetting('waiverDays', Number(e.target.value))} /></label><label>Trade review<input type="number" min="0" value={data.settings.tradeReviewDays} onChange={(e) => updateSetting('tradeReviewDays', Number(e.target.value))} /></label><label>Votes to veto<input type="number" min="0" value={data.settings.vetoVotes} onChange={(e) => updateSetting('vetoVotes', Number(e.target.value))} /></label></div></Panel>
      <Panel title="Playoffs"><div className="form-grid"><label>Playoff teams<input type="number" min="2" value={data.settings.playoffTeams} onChange={(e) => updateSetting('playoffTeams', Number(e.target.value))} /></label><label>Championship week<input type="number" min="14" max="18" value={data.settings.championshipWeek} onChange={(e) => updateSetting('championshipWeek', Number(e.target.value))} /></label><label>Regular season<input type="number" min="1" max="17" value={data.settings.regularSeasonWeeks} onChange={(e) => updateSetting('regularSeasonWeeks', Number(e.target.value))} /></label></div></Panel>
    </div>}

    {commissionerTab === 'Scoring' && <Panel title="Scoring Rules" action={<button className="button compact secondary" type="button" onClick={addScore}><Plus /> Add rule</button>}><div className="scoring-table"><div className="scoring-head"><span>#</span><span>Category</span><span>Rule</span><span>Points</span><span /></div>{data.scoringRules.map((rule, index) => <div key={rule.id}><span>{index + 1}</span><input aria-label={`Rule ${index + 1} category`} value={rule.category} onChange={(e) => updateScore(rule.id, 'category', e.target.value)} /><input aria-label={`${rule.category} rule`} value={rule.rule} onChange={(e) => updateScore(rule.id, 'rule', e.target.value)} /><input aria-label={`${rule.category} points`} type="number" step="0.1" value={rule.points} onChange={(e) => updateScore(rule.id, 'points', e.target.value)} /><button className="icon-button" type="button" aria-label={`Delete ${rule.category}`} onClick={() => setData((current) => ({ ...current, scoringRules: current.scoringRules.filter((item) => item.id !== rule.id) }))}><Trash2 /></button></div>)}</div></Panel>}

    {commissionerTab === 'Rosters' && <div className="settings-grid"><Panel title="Roster Limits"><div className="form-grid"><label>Roster size<input type="number" min="1" value={data.settings.rosterSize} onChange={(e) => updateSetting('rosterSize', Number(e.target.value))} /></label><label>Bench spots<input type="number" min="0" value={data.settings.bench} onChange={(e) => updateSetting('bench', Number(e.target.value))} /></label><label>IR spots<input type="number" min="0" value={data.settings.ir} onChange={(e) => updateSetting('ir', Number(e.target.value))} /></label></div></Panel><Panel title="Starting Lineup"><div className="slot-editor">{Object.entries(data.settings.starters).map(([slot, count]) => <label key={slot}><strong>{slot}</strong><input type="number" min="0" max="8" value={count} onChange={(e) => updateStarter(slot, e.target.value)} /></label>)}</div></Panel></div>}

    {commissionerTab === 'Schedule' && <div className="settings-grid"><Panel title="Schedule Builder"><div className="form-grid"><label className="wide">Matchup format<select value={data.settings.scheduleType} onChange={(e) => updateSetting('scheduleType', e.target.value)}><option>Round robin</option><option>Divisional</option><option>Randomized</option></select></label><label>Regular season weeks<input type="number" min="1" max="17" value={data.settings.regularSeasonWeeks} onChange={(e) => updateSetting('regularSeasonWeeks', Number(e.target.value))} /></label><label>Rivalry week<input type="number" min="1" max="17" value={data.settings.rivalryWeek} onChange={(e) => updateSetting('rivalryWeek', Number(e.target.value))} /></label></div><button className="button secondary" type="button" onClick={onSave}><CalendarDays /> Generate schedule</button></Panel><Panel title="Postseason"><p className="settings-note">Top {data.settings.playoffTeams} teams qualify. Championship is scheduled for Week {data.settings.championshipWeek}.</p></Panel></div>}

    {commissionerTab === 'Managers' && <Panel title="Managers & Teams" action={<button className="button compact primary" type="button" onClick={addManager}><UserPlus /> Invite manager</button>}><div className="manager-table"><div className="manager-head"><span>#</span><span>Team</span><span>Manager</span><span>Role</span><span>Action</span></div>{data.teams.map((team, index) => <div key={team.id}><span>{index + 1}</span><input value={team.name} onChange={(e) => setData((current) => ({ ...current, teams: current.teams.map((item) => item.id === team.id ? { ...item, name: e.target.value } : item) }))} /><input value={team.manager} onChange={(e) => setData((current) => ({ ...current, teams: current.teams.map((item) => item.id === team.id ? { ...item, manager: e.target.value } : item) }))} /><select defaultValue={team.id === 'sybau' ? 'Commissioner' : 'Manager'}><option>Commissioner</option><option>Manager</option><option>Co-manager</option></select><button className="icon-button" type="button" aria-label={`Remove ${team.name}`} onClick={() => setData((current) => ({ ...current, teams: current.teams.filter((item) => item.id !== team.id) }))}><Trash2 /></button></div>)}</div></Panel>}

    {commissionerTab === 'Draft' && <div className="settings-grid"><Panel title="Draft Room"><div className="form-grid"><label className="wide">Draft type<select value={data.settings.draftType} onChange={(e) => updateSetting('draftType', e.target.value)}><option>Snake</option><option>Linear</option><option>Auction</option><option>Offline</option></select></label><label>Seconds per pick<input type="number" min="15" value={data.settings.pickSeconds} onChange={(e) => updateSetting('pickSeconds', Number(e.target.value))} /></label><label className="wide">Draft date<input type="datetime-local" value={data.settings.draftDate} onChange={(e) => updateSetting('draftDate', e.target.value)} /></label></div><Toggle checked={data.settings.pickTrading} onChange={() => updateSetting('pickTrading', !data.settings.pickTrading)} title="Allow draft-pick trading" text="Managers can include future picks in trade offers." /></Panel></div>}

    {commissionerTab === 'Permissions' && <Panel title="Manager Permissions"><div className="permission-list">{Object.entries({ tradeOffers: ['Trade offers', 'Managers can propose player and pick trades.'], tradeVoting: ['Trade voting', 'League members may vote during review.'], rosterEdits: ['Commissioner roster edits', 'Commissioner may correct another team roster.'], leagueChat: ['League chat', 'Managers can post to the league channel.'], coManagers: ['Co-managers', 'Teams may invite a second manager.'] }).map(([key, [title, text]]) => <Toggle key={key} checked={data.settings.permissions[key]} onChange={() => togglePermission(key)} title={title} text={text} />)}</div></Panel>}
  </>
}

function Toggle({ checked, onChange, title, text }) {
  return <label className="toggle-row"><input type="checkbox" checked={checked} onChange={onChange} /><span><strong>{title}</strong><small>{text}</small></span></label>
}
