import { ArrowRight, Check, Menu, Search, Send, X } from 'lucide-react'
import { useState } from 'react'

const nav = [['product', 'Product'], ['commissioners', 'Commissioners'], ['themes', 'League Themes'], ['why', 'Why FFI']]
const roster = [['QB','Trevor Lawrence','JAX','@ KC','19.8'],['RB','Ashton Jeanty','LV','@ DEN','18.7'],['RB','Bhayshul Tuten','JAX','@ KC','10.2'],['WR','Jaxon Smith-Njigba','SEA','SF','17.4'],['WR','Malik Nabers','NYG','@ DAL','15.9'],['TE','Harold Fannin Jr.','CLE','CIN','8.6']]
const themes = [['Liquid Crew','Amber / black / scorecard'],['Sunday Service','Clean / traditional / sharp'],['Bench Warmers','Warm / loud / unserious'],['Gridiron Social Club','Dark / classic / club']]

function RosterPreview({ onEnterDemo }) { return <div className="ffi-roster-preview"><header><strong>FFI</strong><b>My Team</b><span>Liquid Crew⌄</span></header><nav><b>ROSTER</b><span>MATCHUP</span><span>PLAYERS</span><span>LEAGUE</span></nav><main><div><h3>Starters</h3><button type="button" onClick={onEnterDemo}>Set lineup</button></div><header><span>POS</span><span>PLAYER</span><span>OPP</span><span>PROJ</span></header>{roster.map(([pos,player,team,opp,proj])=><div className="ffi-roster-line" key={player}><b>{pos}</b><span><strong>{player}</strong><small>{team}</small></span><span>{opp}</span><strong>{proj}</strong></div>)}</main></div> }

export function MarketingSite({ onEnterDemo }) {
  const [menuOpen,setMenuOpen]=useState(false); const [theme,setTheme]=useState(0)
  const go=(id)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenuOpen(false)}
  return <div className="ffi-brand-site"><header className="ffi-site-header"><a href="#top" className="ffi-site-brand"><strong>FFI</strong><span>THE FANTASY FOOTBALL<br/>INDEPENDENTS</span></a><button className="ffi-site-menu" type="button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button><nav className={menuOpen?'open':''}>{nav.map(([id,label])=><button type="button" key={id} onClick={()=>go(id)}>{label}</button>)}</nav><button className="ffi-gold-button" type="button" onClick={onEnterDemo}>Enter Demo <ArrowRight/></button></header>
  <main id="top">
    <section className="ffi-brand-hero"><div className="ffi-hero-copy"><span className="ffi-margin-note">SAME FRIENDS.<br/>BETTER PLACE<br/>TO BEAT THEM.</span><h1>Fantasy football<br/>for people who<br/>actually like<br/>their league.</h1><p>Set your lineup. Talk your shit. Keep the group together.</p><div><button className="ffi-gold-button" type="button" onClick={onEnterDemo}>Enter the demo <ArrowRight/></button><button className="ffi-outline-button" type="button" onClick={()=>go('product')}>See how it works</button></div></div><div className="ffi-hero-app"><RosterPreview onEnterDemo={onEnterDemo}/><span className="ffi-tape-note">SET LINEUPS<br/>TALK SHIT<br/>WIN TOGETHER.</span></div></section>
    <section className="ffi-rhythm" id="why"><header><h2>The weekly<br/>rhythm.</h2><i>Different days.<br/>Same energy.</i></header>{[['TUESDAY','Waivers','Waivers without the scavenger hunt.'],['THURSDAY','Lineup','Set your lineup. Make your case.'],['SUNDAY','Matchup','Nobody cares about your projection until you win.']].map(([day,title,text])=><article key={day}><b>{day}</b><h3>{title}</h3><p>{text}</p></article>)}<aside>Your league has better stories than their network.</aside></section>
    <section className="ffi-essentials" id="product"><header><h2>The essentials<br/>without the nonsense.</h2><p>All the tools you need. None of the distractions. Standard fantasy workflows, built for real leagues.</p></header><div className="ffi-tools-window"><nav><b>MANAGE</b><span>TRADE</span><span>WAIVERS</span><span>SCORING</span><span>STANDINGS</span></nav><main><label><Search/><input readOnly placeholder="Search players…"/></label><button type="button" onClick={onEnterDemo}>Add / Drop Players</button><button type="button" onClick={onEnterDemo}>Propose Trade</button><button type="button" onClick={onEnterDemo}>View Standings</button></main></div><i>FOOTBALL BRINGS US HERE.<br/>THE PEOPLE KEEP US HERE.</i></section>
    <section className="ffi-clubhouse"><header><h2>A clubhouse.<br/>Not just a platform.</h2><p>Trash talk. Trade talk. Group chat. Keep the league in one place and the stories going all season.</p></header><div className="ffi-chat"><nav><b>League Chat</b><span>Trades</span><span>Announcements</span></nav>{[['TG','Tim Garcia','Putting in a claim. Let’s see if anyone’s paying attention.'],['AS','Ann','Too late. Already on it.'],['CM','Commissioner','Lineups due Thursday. No excuses.']].map(([initials,name,message])=><p key={name}><b>{initials}</b><span><strong>{name}</strong>{message}</span></p>)}<label><input readOnly placeholder="Talk your shit…"/><Send/></label></div><aside><strong>GOOD LEAGUES.</strong><b>GOOD PEOPLE.</b><span>Built for the group chat.</span></aside></section>
    <section className="ffi-own-it" id="themes"><header><h2>Make it yours.</h2><p>FFI carries the Liquid Crew attitude. Each league supplies its own personality.</p><button className="ffi-outline-button" type="button" onClick={onEnterDemo}>Explore league themes <ArrowRight/></button></header><div className="ffi-theme-demo"><div><span className="ffi-lc-mark">LC</span><h3>{themes[theme][0]}</h3><small>{themes[theme][1]}</small></div><main><h3>Your league. Your look.</h3><p>Names, logos, colors, language, awards, and history—without changing how fantasy works.</p><div>{themes.map(([name],index)=><button className={theme===index?'active':''} key={name} type="button" onClick={()=>setTheme(index)}>{name}</button>)}</div></main></div></section>
    <section className="ffi-commish" id="commissioners"><header><h2>Commissioners<br/>run a tight league.</h2><p>Flexible controls. Clear tools. Less headache, more football.</p></header><ul>{['Customize scoring settings','Manage waivers and trade rules','Edit league settings','Send announcements','Keep your league on track'].map(item=><li key={item}><Check/>{item}</li>)}</ul><button className="ffi-gold-button" type="button" onClick={onEnterDemo}>Commissioner tools <ArrowRight/></button><aside>GOOD COMMISSIONERS<br/>KEEP GOOD FRIENDS.</aside></section>
    <section className="ffi-move"><article><h2>Bring your league<br/>with you.</h2><p>Easy import from other platforms. Same history. New home.</p><button className="ffi-outline-button" type="button">Import your league <ArrowRight/></button></article><article><h2>Ready for<br/>what’s next.</h2><p>Prepared for licensed schedules, stats, injuries, projections, and odds feeds.</p><button className="ffi-outline-button" type="button" onClick={()=>go('why')}>Accurate data. Real football. <ArrowRight/></button></article><aside>THE GAME CHANGES.<br/>GOOD LEAGUES DON’T.</aside></section>
    <section className="ffi-last-call"><div><h2>Fantasy football is better together.</h2><p>Enter the demo and see what your league can do.</p></div><button className="ffi-gold-button" type="button" onClick={onEnterDemo}>Enter the demo <ArrowRight/></button></section>
  </main><footer className="ffi-site-footer"><div className="ffi-site-brand"><strong>FFI</strong><span>THE FANTASY FOOTBALL<br/>INDEPENDENTS</span></div><p>Leagues make life better.</p><nav>{nav.map(([id,label])=><button type="button" key={id} onClick={()=>go(id)}>{label}</button>)}</nav><i>GOOD LEAGUES<br/>LAST LONGER.</i></footer></div>
}
